name: TD builder

on:
  push: 
    tags: 
      - '[vV][1-9].*.*'

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - uses: pnpm/action-setup@v4.1.0
      with:
        version: 8.14.0
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Build
      run: | 
        pnpm install
        pnpm dist

    - name: Build and release
      uses: actions/upload-artifact@v4
      with:
        name: td-build-${{ github.ref_name }}
        path: 
          dist/win-unpacked
      
